apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xgzs1bldy-go 
  janus-idp.io/tekton: xgzs1bldy-go
  backstage.io/kubernetes-id: xgzs1bldy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xgzs1bldy-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  